projects:
  restaurantapp:
    schemaPath: src/graphql/schema.json
    includes:
      - src/graphql/**/*.js
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: javascript
        generatedFileName: ''
        docsFilePath: src/graphql
        graphQLApiId: yaodjmf5wbahvlps4er7siaijq
      endpoints:
        prod: >-
          https://tgpdzhn6gbahlfk4lkseoyt36a.appsync-api.us-west-2.amazonaws.com/graphql
