// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "us-west-2",
    "aws_appsync_graphqlEndpoint": "https://tgpdzhn6gbahlfk4lkseoyt36a.appsync-api.us-west-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-west-2",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-nc44gts6bzcbtnjca4jtlzuegy"
};


export default awsmobile;
